apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
  - name: ip-app
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-vol
      mountPath: /app/pvc-volume
  volumes: 
  - name: pvc-vol
    persistentVolumeClaim:
        claimName: my-pvc
